// formulaire/resources/js/Pages/composents/Input.vue
<script lang="ts" setup>
    const props = defineProps({
        id: String,
        type: String,
        label: String,
        modelValue: [String, Number]
    });

    const emit = defineEmits(['update:modelValue'])
</script>
<template>
    <div class="input-box flex flex-col w-full">        
        <label :for="props.id">{{props.label}}</label>
        <input :type="props.type" :value="props.modelValue" v-on:input="$event => emit('update:modelValue', $event.target.value)" class="p-3 w-full h-5 outline-none border-0 border-b-2 border-slate-300" :id="props.id">
    </div>
</template>

// react-inertia-app/resources/js/Pages/component/Input.jsx
/**
 * 
 * @param {string} value 
 * @param {string} type
 * @param {string} name
 * @returns {HTMLElement}
 */
export function InputBox({label , type, name, id}){
    return (<div className='flex flex-col w-full gap-1'>
                <label htmlFor={id} className="text-sm">{label}</label>
                <input type={type} name={name} className='border-2 p-1 px-2 outline-none' id={id}/>
            </div>)
}
